#!/usr/bin/env lua
-- Script to load one or more codespell dictionary files and output
-- a single merged file.

-- Requires Lua penlight.

-- Use the preprocessWikipediaContent.sh script on any text copied right
-- from the Wikipedia page before passing it to this script: it cleans it
-- and adds the necessary trailing commas.

--[[ Original Author: Ryan Pavlik <rpavlik@iastate.edu> <abiryan@ryand.net>
Copyright 2012 Iowa State University.
Distributed under the Boost Software License, Version 1.0.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
]]


require "strict"

-- Requires lua penlight
-- Looks relative to this file.
local app = require "pl.app"
app.require_here "modules"

local CorrectionDatabase = require "CorrectionDatabase"

data = CorrectionDatabase()

outfn = "outputdict.txt"

local lastTypos = 0
local lastCorrections = 0
for _, fn in ipairs(arg) do
	print("Loading file", fn)
	local f = assert(io.open(fn, "r"))
	for line in f:lines() do
		--[[local parsed = CorrectionUtils.parseLine(line)
		CorrectionUtils.printCorrection(parsed)
		print(CorrectionUtils.serializeCorrection(parsed))]]
		data:add(line)
	end
	f:close()
	local typos, corrections = data:getCounts()
	print("Current incorrect spelling and corrections counts:")
	print( ("%d [+%d] incorrect spellings, %d [+%d] corrections\n"):format(
			typos,
			typos - lastTypos,
			corrections,
			corrections - lastCorrections)
	)
	lastTypos = typos
	lastCorrections = corrections
end

print("Writing unified database out to:", outfn)
local f = assert(io.open(outfn, "wb"))
f:write(data:serialize())
f:close()

